services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.12.2
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
    ports:
      - "9200:9200"
